# Generated by Django 5.2.6 on 2025-11-19 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_types_id_alter_contacts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_types',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
