# Generated by Django 5.2.6 on 2025-11-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_types_id_alter_contacts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_types',
            name='type_name',
            field=models.CharField(choices=[('Client', 'client'), ('Fournisseur', 'fournisseur'), ('Employé', 'employé'), ('Actionnaire', 'actionnaire'), ('Banque', 'banque'), ('Administration', 'administration'), ('Autre', 'autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_types_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='contacts.contact_types'),
        ),
    ]
