# Generated by Django 5.2.5 on 2025-11-09 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        ('company_organization', '0005_alter_company_settings_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='chart_of_accounts.account_types'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_organization.company'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='parent_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to='chart_of_accounts.accounts'),
        ),
    ]
