# Generated by Django 5.2.5 on 2025-11-11 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0002_alter_accounts_account_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_types',
            name='normal_balance',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Debit/Credit', 'Debit/Credit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.account_types'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='parent_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounts'),
        ),
    ]
