# Generated by Django 5.2.6 on 2025-11-19 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0004_alter_account_types_id_alter_accounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_types',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
