# Generated by Django 5.2.6 on 2025-11-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0005_alter_account_types_id_alter_accounts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='chart_of_accounts.account_types'),
        ),
    ]
