# Generated by Django 5.2.5 on 2025-11-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        ('company_organization', '0001_initial'),
        ('contacts', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement_Methods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(choices=[('espèce', 'espèce'), ('chèque', 'Chèque'), ('carte de crédit', 'Carte de crédit'), ('tranfert banquaire', 'Tranfert banquaire')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payement_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounts')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_organization.company')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacts')),
                ('payement_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payements.payement_methods')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Allocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_date', models.DateField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoices')),
                ('payement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payements.payements')),
            ],
        ),
    ]
