# Generated by Django 5.2.6 on 2025-12-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
        ('contacts', '0005_alter_contact_types_type_name_and_more'),
        ('payements', '0003_alter_payement_methods_id_alter_payements_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payements',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_for_payement', to='company_organization.company'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_for_payement', to='contacts.contacts'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='payement_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='payements.payement_methods'),
        ),
        migrations.AlterField(
            model_name='payment_allocations',
            name='payement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='payements.payements'),
        ),
    ]
