# Generated by Django 5.2.6 on 2025-11-28 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('bilan', 'Bilan'), ('compte_de_resultat', 'Compte de résultat'), ('flux_de_tresorerie', 'Flux de trésorerie'), ('balance_comptable', 'Balance comptable')], max_length=100)),
                ('report_date', models.DateField()),
                ('report_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_company', to='company_organization.company')),
            ],
        ),
    ]
