# Generated by Django 5.2.5 on 2025-11-14 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0004_alter_account_types_id_alter_accounts_id'),
        ('company_organization', '0008_alter_company_id_alter_company_settings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Rates',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_organization.company')),
                ('tax_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounts')),
            ],
        ),
    ]
