# Generated by Django 5.2.5 on 2025-11-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0001_initial'),
        ('company_organization', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=100)),
                ('journal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50)),
                ('entry_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publié', 'Publié'), ('annulé', 'Annulé')], default='draft', max_length=10)),
                ('created_by', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_organization.company')),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_transactions.journals')),
            ],
        ),
        migrations.CreateModel(
            name='Journal_Entry_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('line_number', models.IntegerField(blank=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounts')),
                ('contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contacts')),
                ('entry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_transactions.journal_entries')),
            ],
        ),
    ]
