# Generated by Django 5.2.5 on 2025-11-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_transactions', '0002_alter_journal_entries_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal_entries',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry_items',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry_items',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
