# Generated by Django 5.2.6 on 2025-11-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_of_accounts', '0006_alter_accounts_account_type_id'),
        ('journal_transactions', '0004_alter_journal_entries_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry_items',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='chart_of_accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='journal_entry_items',
            name='entry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal_transactions.journal_entries'),
        ),
    ]
