# Generated by Django 5.2.5 on 2025-11-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_settings',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='company_organization.company'),
        ),
    ]
