# Generated by Django 5.2.5 on 2025-11-14 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0007_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company_settings',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
