# Generated by Django 5.2.6 on 2025-12-07 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_security', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Permissions',
            new_name='User_Permission',
        ),
    ]
