# Generated by Django 5.2.6 on 2025-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_security', '0002_rename_user_permissions_user_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Permission',
            new_name='User_Permissions',
        ),
    ]
