# Generated by Django 5.2.6 on 2025-12-07 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_security', '0003_rename_user_permission_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(choices=[('invoicing', 'Invoicing'), ('payements', 'Payements'), ('reports', 'Reports'), ('chart_of_accounts', 'Chart of Accounts'), ('contacts', 'Contacts'), ('journal_entries', 'Journal Entries'), ('inventory', 'Inventory'), ('tax_management', 'Tax Management')], max_length=50)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Permissions',
        ),
    ]
