# Generated by Django 5.2.6 on 2025-12-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
        ('users_security', '0004_userpermissions_delete_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_company', to='company_organization.company'),
        ),
    ]
