# Generated by Django 5.2.6 on 2025-11-20 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
        ('contacts', '0005_alter_contact_types_type_name_and_more'),
        ('invoicing', '0004_alter_invoices_id_alter_invoices_lines_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company_organization.company'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='contact_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='contacts.contacts'),
        ),
        migrations.AlterField(
            model_name='invoices_lines',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_lines', to='invoicing.invoices'),
        ),
    ]
