# Generated by Django 5.2.6 on 2025-11-21 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_invoices_company_id_alter_invoices_contact_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices_lines',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='invoicing.invoices'),
        ),
    ]
