# Generated by Django 5.2.6 on 2025-11-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
        ('invoicing', '0006_alter_invoices_lines_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to='company_organization.company'),
        ),
    ]
