# Generated by Django 5.2.5 on 2025-11-14 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chart_of_accounts', '0004_alter_account_types_id_alter_accounts_id'),
        ('company_organization', '0008_alter_company_id_alter_company_settings_id'),
        ('invoicing', '0003_alter_invoices_id_alter_invoices_lines_id'),
        ('journal_transactions', '0002_alter_journal_entries_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('cogs_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chart_of_accounts.accounts')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_organization.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Transactions',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('achat', 'Achat'), ('vente', 'Vente'), ('ajustement', 'Ajustement'), ('retour', 'Retour')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField()),
                ('reference_type', models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('journal_entry', 'Journal Entry')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.invoices')),
                ('journal_entry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal_transactions.journal_entries')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
    ]
