# Generated by Django 5.2.6 on 2025-11-28 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organization', '0010_alter_company_settings_company_id'),
        ('inventory', '0002_alter_inventory_transactions_id_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_transactions',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='inventory.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to='company_organization.company'),
        ),
    ]
